import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'herald_backend.settings')
django.setup()

from django.db import connection

print("🔧 CREATING DJANGO_ADMIN_LOG TABLE")
print("=" * 50)

with connection.cursor() as cursor:
    # Check if django_admin_log exists
    cursor.execute("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_name = 'django_admin_log'
        );
    """)
    admin_log_exists = cursor.fetchone()[0]
    
    if not admin_log_exists:
        print("📝 Creating django_admin_log table...")
        cursor.execute("""
            CREATE TABLE django_admin_log (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                action_time TIMESTAMP WITH TIME ZONE NOT NULL,
                user_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                content_type_id INTEGER REFERENCES django_content_type(id) ON DELETE CASCADE,
                object_id TEXT,
                object_repr VARCHAR(200) NOT NULL,
                action_flag SMALLINT NOT NULL CHECK (action_flag >= 0),
                change_message TEXT NOT NULL
            );
        """)
        print("✅ django_admin_log table created")
        
        # Create indexes
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb 
            ON django_admin_log(content_type_id);
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6 
            ON django_admin_log(user_id);
        """)
        print("✅ Indexes created")
    else:
        print("✅ django_admin_log table already exists")

print("\n" + "=" * 50)
print("✅ Setup complete! Try accessing http://127.0.0.1:8000/admin/ now")