services:
  - type: web
    name: herald-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate_safe && (python manage.py seed_data --traceback || echo 'seed_data failed, skipping')"
    startCommand: "gunicorn herald_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: herald-backend-6i3m.onrender.com
      - key: RENDER
        value: true