# Generated by Django 6.0.2 on 2026-03-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_adcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='cta_text',
            field=models.CharField(default='Learn More', max_length=100),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='reward_points',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='target_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
