# Generated by Django 6.0.2 on 2026-03-18 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0001_initial'),
        ('users', '0003_directmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='livestreams.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_chat_messages', to='users.user')),
            ],
            options={
                'db_table': 'stream_chat_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('points', 'HTTN Points'), ('tokens', 'HTTN Tokens'), ('espees', 'Espees')], default='espees', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='livestreams.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_donations', to='users.user')),
            ],
            options={
                'db_table': 'stream_donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamViewerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('join', 'Join'), ('leave', 'Leave')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_events', to='livestreams.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_viewer_events', to='users.user')),
            ],
            options={
                'db_table': 'stream_viewer_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
