# Generated by Django 6.0.2 on 2026-03-03 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('httn_points', models.IntegerField(default=0)),
                ('httn_tokens', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('espees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_rewards', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
